version: '3.7'

services:
  loadbalance:
    image: nginx:1.13.1
    container_name: laravel-loadbalance
    depends_on:
      - laravel
      - socketio
    expose:
      - 80
      - 443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: fr6.milkiland.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: fr6.milkiland.org
      LETSENCRYPT_EMAIL: admin@milkiland.com
    networks:
      proxy:
      default:

  laravel:
    image: laravel
    container_name: laravel
    restart: always
    depends_on:
      - mysql
      - redis
      - socketio
    networks:
      default:
        aliases:
          - laravel
    volumes:
     - ./app:/app
     - ./mail:/etc/ssmtp
    ports:
     - '2380:80'
    expose:
      - 80

  laravel_worker:
    image: laravel
    container_name: laravel-worker
    restart: always
    depends_on:
      - mysql
      - redis
      - socketio
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Starting queue workers and scheduler'
        /start.sh
        echo 'Starting apache'
        exec apache2-foreground
    networks:
      default:
        aliases:
          - laravel_worker
    volumes:
     - ./app:/app
     - ./mail:/etc/ssmtp
     - ./worker/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf:ro
    expose:
      - 80


  mysql:
    image: mariadb:10.4.11
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel-mysql
    networks:
      default:
        aliases:
          - mysql
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0.7
    container_name: laravel-redis
    restart: always
    networks:
      default:
        aliases:
          - redis
    volumes:
      - ./redis:/data

  socketio:
    image: mintopia/laravel-echo-server
    restart: always
    container_name: laravel-socketio
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - socketio
    expose:
      - 6001
    ports:
      - "6001:6001"
    environment:
      - LARAVEL_ECHO_SERVER_AUTH_HOST=http://laravel
      - LARAVEL_ECHO_SERVER_DEBUG=true
      - ECHO_DEVMODE=true
      - ECHO_PROTOCOL=http
      - ECHO_REDIS_PORT=6379
      - ECHO_REDIS_HOSTNAME=redis
      - ECHO_ALLOW_CORS=true
      - ECHO_ALLOW_ORIGIN=http://fr6.milkiland.org

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 2381:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
