version: '3.7'

services:
  laravel:
    image: laravel
    container_name: laravel
    restart: always
    depends_on:
      - mysql
      - redis
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Starting queue workers and scheduler'
        /start.sh
        echo 'Starting apache'
        exec apache2-foreground
    networks:
      proxy:
      default:
        aliases:
          - laravel
    volumes:
     - ./app:/app
     - ./mail:/etc/ssmtp
    ports:
     - '2380:80'
    expose:
      - 80
    environment:
      VIRTUAL_HOST: fr6.milkiland.org
      LETSENCRYPT_HOST: fr6.milkiland.org
      LETSENCRYPT_EMAIL: admin@milkiland.com

  mysql:
    image: mariadb:10.4.11
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel_mysql
    networks:
      default:
        aliases:
          - mysql
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0.7
    container_name: laravel_redis
    restart: always
    networks:
      default:
        aliases:
          - redis
    volumes:
      - ./redis:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 2381:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
