version: '3.7'

services:
  loadbalance:
    image: nginx:1.13.1
    restart: always
    container_name: laravel-loadbalance
    depends_on:
      - laravel
      - socketio
    ports:
      - 2380:80
    expose:
      - 80
      - 443
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      proxy:
      default:
        aliases:
          - laravelnginx

  laravel:
    image: maximmonin/laravel
    container_name: laravel
    restart: always
    depends_on:
      - mysql
      - redis
      - socketio
    networks:
      default:
        aliases:
          - laravel
    volumes:
     - ./app:/app
     - ./mail:/etc/ssmtp
     - ./worker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 9000

  laravel_worker:
    image: maximmonin/laravel
    container_name: laravel-worker
    restart: always
    depends_on:
      - mysql
      - redis
      - socketio
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Starting queue workers and scheduler'
        /start.sh
        echo 'Starting php-fpm'
        exec php-fpm
    networks:
      default:
        aliases:
          - laravel_worker
    volumes:
     - ./app:/app
     - ./mail:/etc/ssmtp
     - ./worker/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf:ro
     - ./worker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 9000

  mysql:
    image: mariadb:10.4.11
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel-mysql
    networks:
      default:
        aliases:
          - mysql
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0.7
    container_name: laravel-redis
    restart: always
    networks:
      default:
        aliases:
          - redis
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro

  socketio:
    image: mintopia/laravel-echo-server
    restart: always
    container_name: laravel-socketio
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - socketio
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 6001
    ports:
      - "6001:6001"
    environment:
      - LARAVEL_ECHO_SERVER_AUTH_HOST=http://laravelnginx
      - LARAVEL_ECHO_SERVER_DEBUG=true
      - ECHO_DEVMODE=true
      - ECHO_PROTOCOL=http
      - ECHO_REDIS_PORT=6379
      - ECHO_REDIS_HOSTNAME=redis
      - ECHO_ALLOW_CORS
      - ECHO_ALLOW_ORIGIN

  selenium:
    image: selenium/hub
    restart: always
    container_name: laravel-selenium
    depends_on:
      - loadbalance
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=30000 
    networks:
      default:
        aliases:
          - selenium

  selenium-chrome:
    image: selenium/node-chrome
    restart: always
    container_name: laravel-selenium-chrome
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:

  selenium-firefox:
    image: selenium/node-firefox
    restart: always
    container_name: laravel-selenium-firefox
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 2381:80
    networks:
      default:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
